using namespace std;

namespace watchData {
	const int preprocessId = 0;
	const int spawnTimeId = 1;
	const int despawnTimeId = 2;
	const int initializeId = 3;
	const int updateSequentialId = 4;
	const int updateParallelId = 5;
	const int terminateId = 6;
	const int updateSpawnId = 7;
	const int RuntimeEnvironmentId = 1000;
	const int RuntimeUpdateId = 1001;
	const int RuntimeSkconst intransformId = 1002;
	const int RuntimeParticleTransformId = 1003;
	const int RuntimeBackgroundId = 1004;
	const int RuntimeUIId = 1005;
	const int RuntimeUIConfigurationId = 1006;
	const int LevelMemoryId = 2000;
	const int LevelDataId = 2001;
	const int LevelOptionId = 2002;
	const int LevelScoreId = 2003;
	const int LevelLifeId = 2004;
	const int EngineRomId = 3000;
	const int EntityMemoryId = 4000;
	const int EntityDataId = 4001;
	const int EntitySharedMemoryId = 4002;
	const int EntityInfoId = 4003;
	const int EntityInputId = 4004;
	const int EntityDataArrayId = 4101;
	const int EntitySharedMemoryArrayId = 4102;
	const int EntityInfoArrayId = 4103;
	const int ArchetypeLifeId = 5000;
	const int TemporaryMemoryId = 10000;
	
	Pointer<RuntimeEnvironmentId> RuntimeEnvironment;
	Pointer<RuntimeUpdateId> RuntimeUpdate;
	Pointer<RuntimeSkinTransformId> RuntimeSkinTransform;
	Pointer<RuntimeParticleTransformId> RuntimeParticleTransform;
	Pointer<RuntimeBackgroundId> RuntimeBackground;
	Pointer<RuntimeUIId> RuntimeUI;
	Pointer<RuntimeUIConfigurationId> RuntimeUIConfiguration;
	Pointer<LevelMemoryId> LevelMemory;
	Pointer<LevelDataId> LevelData;
	Pointer<LevelOptionId> LevelOption;
	Pointer<LevelScoreId> LevelScore;
	Pointer<LevelLifeId> LevelLife;
	Pointer<EngineRomId> EngineRom;
	Pointer<EntityMemoryId> EntityMemory;
	Pointer<EntityDataId> EntityData;
	Pointer<EntitySharedMemoryId> EntitySharedMemory;
	Pointer<EntityInfoId> EntityInfo;
	Pointer<EntityInputId> EntityInput;
	Pointer<EntityDataArrayId> EntityDataArray;
	Pointer<EntitySharedMemoryArrayId> EntitySharedMemoryArray;
	Pointer<EntityInfoArrayId> EntityInfoArray;
	Pointer<ArchetypeLifeId> ArchetypeLife;
	Pointer<TemporaryMemoryId> TemporaryMemory;
	
	bool readMap[10001][8]; 
	bool writeMap[10001][8];
	bool initializeReadWriteTable = [](){
		memset(readMap, 0, sizeof readMap); memset(writeMap, 0 sizeof writeMap);
		writeMap[RuntimeEnvironmentId][preprocessId] = 1; writeMap[RuntimeEnvironmentId][spawnTimeId] = 1; writeMap[RuntimeEnvironmentId][despawnTimeId] = 1; writeMap[RuntimeEnvironmentId][initializeId] = 1; writeMap[RuntimeEnvironmentId][updateSequentialId] = 1; writeMap[RuntimeEnvironmentId][updateParallelId] = 1; writeMap[RuntimeEnvironmentId][terminateId] = 1; writeMap[RuntimeEnvironmentId][updateSpawnId] = 1; 
		readMap[RuntimeEnvironmentId][preprocessId] = 1; 
		writeMap[RuntimeUpdateId][preprocessId] = 1; writeMap[RuntimeUpdateId][spawnTimeId] = 1; writeMap[RuntimeUpdateId][despawnTimeId] = 1; writeMap[RuntimeUpdateId][initializeId] = 1; writeMap[RuntimeUpdateId][updateSequentialId] = 1; writeMap[RuntimeUpdateId][updateParallelId] = 1; writeMap[RuntimeUpdateId][terminateId] = 1; writeMap[RuntimeUpdateId][updateSpawnId] = 1; 
		writeMap[RuntimeSkinTransformId][preprocessId] = 1; writeMap[RuntimeSkinTransformId][spawnTimeId] = 1; writeMap[RuntimeSkinTransformId][despawnTimeId] = 1; writeMap[RuntimeSkinTransformId][initializeId] = 1; writeMap[RuntimeSkinTransformId][updateSequentialId] = 1; writeMap[RuntimeSkinTransformId][updateParallelId] = 1; writeMap[RuntimeSkinTransformId][terminateId] = 1; writeMap[RuntimeSkinTransformId][updateSpawnId] = 1; 
		readMap[RuntimeSkinTransformId][preprocessId] = 1; readMap[RuntimeSkinTransformId][updateSequentialId] = 1; 
		writeMap[RuntimeParticleTransformId][preprocessId] = 1; writeMap[RuntimeParticleTransformId][spawnTimeId] = 1; writeMap[RuntimeParticleTransformId][despawnTimeId] = 1; writeMap[RuntimeParticleTransformId][initializeId] = 1; writeMap[RuntimeParticleTransformId][updateSequentialId] = 1; writeMap[RuntimeParticleTransformId][updateParallelId] = 1; writeMap[RuntimeParticleTransformId][terminateId] = 1; writeMap[RuntimeParticleTransformId][updateSpawnId] = 1; 
		readMap[RuntimeParticleTransformId][preprocessId] = 1; readMap[RuntimeParticleTransformId][updateSequentialId] = 1; 
		writeMap[RuntimeBackgroundId][preprocessId] = 1; writeMap[RuntimeBackgroundId][spawnTimeId] = 1; writeMap[RuntimeBackgroundId][despawnTimeId] = 1; writeMap[RuntimeBackgroundId][initializeId] = 1; writeMap[RuntimeBackgroundId][updateSequentialId] = 1; writeMap[RuntimeBackgroundId][updateParallelId] = 1; writeMap[RuntimeBackgroundId][terminateId] = 1; writeMap[RuntimeBackgroundId][updateSpawnId] = 1; 
		readMap[RuntimeBackgroundId][preprocessId] = 1; readMap[RuntimeBackgroundId][updateSequentialId] = 1; 
		writeMap[RuntimeUIId][preprocessId] = 1; writeMap[RuntimeUIId][spawnTimeId] = 1; writeMap[RuntimeUIId][despawnTimeId] = 1; writeMap[RuntimeUIId][initializeId] = 1; writeMap[RuntimeUIId][updateSequentialId] = 1; writeMap[RuntimeUIId][updateParallelId] = 1; writeMap[RuntimeUIId][terminateId] = 1; writeMap[RuntimeUIId][updateSpawnId] = 1; 
		readMap[RuntimeUIId][preprocessId] = 1; 
		writeMap[RuntimeUIConfigurationId][preprocessId] = 1; writeMap[RuntimeUIConfigurationId][spawnTimeId] = 1; writeMap[RuntimeUIConfigurationId][despawnTimeId] = 1; writeMap[RuntimeUIConfigurationId][initializeId] = 1; writeMap[RuntimeUIConfigurationId][updateSequentialId] = 1; writeMap[RuntimeUIConfigurationId][updateParallelId] = 1; writeMap[RuntimeUIConfigurationId][terminateId] = 1; writeMap[RuntimeUIConfigurationId][updateSpawnId] = 1; 
		readMap[RuntimeUIConfigurationId][preprocessId] = 1; 
		writeMap[LevelMemoryId][preprocessId] = 1; writeMap[LevelMemoryId][spawnTimeId] = 1; writeMap[LevelMemoryId][despawnTimeId] = 1; writeMap[LevelMemoryId][initializeId] = 1; writeMap[LevelMemoryId][updateSequentialId] = 1; writeMap[LevelMemoryId][updateParallelId] = 1; writeMap[LevelMemoryId][terminateId] = 1; writeMap[LevelMemoryId][updateSpawnId] = 1; 
		readMap[LevelMemoryId][preprocessId] = 1; readMap[LevelMemoryId][updateSequentialId] = 1; 
		writeMap[LevelDataId][preprocessId] = 1; writeMap[LevelDataId][spawnTimeId] = 1; writeMap[LevelDataId][despawnTimeId] = 1; writeMap[LevelDataId][initializeId] = 1; writeMap[LevelDataId][updateSequentialId] = 1; writeMap[LevelDataId][updateParallelId] = 1; writeMap[LevelDataId][terminateId] = 1; writeMap[LevelDataId][updateSpawnId] = 1; 
		readMap[LevelDataId][preprocessId] = 1; 
		writeMap[LevelOptionId][preprocessId] = 1; writeMap[LevelOptionId][spawnTimeId] = 1; writeMap[LevelOptionId][despawnTimeId] = 1; writeMap[LevelOptionId][initializeId] = 1; writeMap[LevelOptionId][updateSequentialId] = 1; writeMap[LevelOptionId][updateParallelId] = 1; writeMap[LevelOptionId][terminateId] = 1; writeMap[LevelOptionId][updateSpawnId] = 1; 
		writeMap[LevelScoreId][preprocessId] = 1; writeMap[LevelScoreId][spawnTimeId] = 1; writeMap[LevelScoreId][despawnTimeId] = 1; writeMap[LevelScoreId][initializeId] = 1; writeMap[LevelScoreId][updateSequentialId] = 1; writeMap[LevelScoreId][updateParallelId] = 1; writeMap[LevelScoreId][terminateId] = 1; writeMap[LevelScoreId][updateSpawnId] = 1; 
		readMap[LevelScoreId][preprocessId] = 1; 
		writeMap[LevelLifeId][preprocessId] = 1; writeMap[LevelLifeId][spawnTimeId] = 1; writeMap[LevelLifeId][despawnTimeId] = 1; writeMap[LevelLifeId][initializeId] = 1; writeMap[LevelLifeId][updateSequentialId] = 1; writeMap[LevelLifeId][updateParallelId] = 1; writeMap[LevelLifeId][terminateId] = 1; writeMap[LevelLifeId][updateSpawnId] = 1; 
		readMap[LevelLifeId][preprocessId] = 1; 
		writeMap[EngineRomId][preprocessId] = 1; writeMap[EngineRomId][spawnTimeId] = 1; writeMap[EngineRomId][despawnTimeId] = 1; writeMap[EngineRomId][initializeId] = 1; writeMap[EngineRomId][updateSequentialId] = 1; writeMap[EngineRomId][updateParallelId] = 1; writeMap[EngineRomId][terminateId] = 1; writeMap[EngineRomId][updateSpawnId] = 1; 
		writeMap[EntityMemoryId][preprocessId] = 1; writeMap[EntityMemoryId][spawnTimeId] = 1; writeMap[EntityMemoryId][despawnTimeId] = 1; writeMap[EntityMemoryId][initializeId] = 1; writeMap[EntityMemoryId][updateSequentialId] = 1; writeMap[EntityMemoryId][updateParallelId] = 1; writeMap[EntityMemoryId][terminateId] = 1; 
		readMap[EntityMemoryId][preprocessId] = 1; readMap[EntityMemoryId][spawnTimeId] = 1; readMap[EntityMemoryId][despawnTimeId] = 1; readMap[EntityMemoryId][initializeId] = 1; readMap[EntityMemoryId][updateSequentialId] = 1; readMap[EntityMemoryId][updateParallelId] = 1; readMap[EntityMemoryId][terminateId] = 1; 
		writeMap[EntityDataId][preprocessId] = 1; writeMap[EntityDataId][spawnTimeId] = 1; writeMap[EntityDataId][despawnTimeId] = 1; writeMap[EntityDataId][initializeId] = 1; writeMap[EntityDataId][updateSequentialId] = 1; writeMap[EntityDataId][updateParallelId] = 1; writeMap[EntityDataId][terminateId] = 1; 
		readMap[EntityDataId][preprocessId] = 1; 
		writeMap[EntitySharedMemoryId][preprocessId] = 1; writeMap[EntitySharedMemoryId][spawnTimeId] = 1; writeMap[EntitySharedMemoryId][despawnTimeId] = 1; writeMap[EntitySharedMemoryId][initializeId] = 1; writeMap[EntitySharedMemoryId][updateSequentialId] = 1; writeMap[EntitySharedMemoryId][updateParallelId] = 1; writeMap[EntitySharedMemoryId][terminateId] = 1; 
		readMap[EntitySharedMemoryId][preprocessId] = 1; readMap[EntitySharedMemoryId][updateSequentialId] = 1; 
		writeMap[EntityInfoId][preprocessId] = 1; writeMap[EntityInfoId][spawnTimeId] = 1; writeMap[EntityInfoId][despawnTimeId] = 1; writeMap[EntityInfoId][initializeId] = 1; writeMap[EntityInfoId][updateSequentialId] = 1; writeMap[EntityInfoId][updateParallelId] = 1; writeMap[EntityInfoId][terminateId] = 1; 
		writeMap[EntityInputId][preprocessId] = 1; writeMap[EntityInputId][spawnTimeId] = 1; writeMap[EntityInputId][despawnTimeId] = 1; writeMap[EntityInputId][initializeId] = 1; writeMap[EntityInputId][updateSequentialId] = 1; writeMap[EntityInputId][updateParallelId] = 1; writeMap[EntityInputId][terminateId] = 1; 
		readMap[EntityInputId][preprocessId] = 1; 
		writeMap[EntityDataArrayId][preprocessId] = 1; writeMap[EntityDataArrayId][spawnTimeId] = 1; writeMap[EntityDataArrayId][despawnTimeId] = 1; writeMap[EntityDataArrayId][initializeId] = 1; writeMap[EntityDataArrayId][updateSequentialId] = 1; writeMap[EntityDataArrayId][updateParallelId] = 1; writeMap[EntityDataArrayId][terminateId] = 1; writeMap[EntityDataArrayId][updateSpawnId] = 1; 
		readMap[EntityDataArrayId][preprocessId] = 1; 
		writeMap[EntitySharedMemoryArrayId][preprocessId] = 1; writeMap[EntitySharedMemoryArrayId][spawnTimeId] = 1; writeMap[EntitySharedMemoryArrayId][despawnTimeId] = 1; writeMap[EntitySharedMemoryArrayId][initializeId] = 1; writeMap[EntitySharedMemoryArrayId][updateSequentialId] = 1; writeMap[EntitySharedMemoryArrayId][updateParallelId] = 1; writeMap[EntitySharedMemoryArrayId][terminateId] = 1; writeMap[EntitySharedMemoryArrayId][updateSpawnId] = 1; 
		readMap[EntitySharedMemoryArrayId][preprocessId] = 1; readMap[EntitySharedMemoryArrayId][updateSequentialId] = 1; 
		writeMap[EntityInfoArrayId][preprocessId] = 1; writeMap[EntityInfoArrayId][spawnTimeId] = 1; writeMap[EntityInfoArrayId][despawnTimeId] = 1; writeMap[EntityInfoArrayId][initializeId] = 1; writeMap[EntityInfoArrayId][updateSequentialId] = 1; writeMap[EntityInfoArrayId][updateParallelId] = 1; writeMap[EntityInfoArrayId][terminateId] = 1; writeMap[EntityInfoArrayId][updateSpawnId] = 1; 
		writeMap[ArchetypeLifeId][preprocessId] = 1; writeMap[ArchetypeLifeId][spawnTimeId] = 1; writeMap[ArchetypeLifeId][despawnTimeId] = 1; writeMap[ArchetypeLifeId][initializeId] = 1; writeMap[ArchetypeLifeId][updateSequentialId] = 1; writeMap[ArchetypeLifeId][updateParallelId] = 1; writeMap[ArchetypeLifeId][terminateId] = 1; writeMap[ArchetypeLifeId][updateSpawnId] = 1; 
		readMap[ArchetypeLifeId][preprocessId] = 1; 
		writeMap[TemporaryMemoryId][preprocessId] = 1; writeMap[TemporaryMemoryId][spawnTimeId] = 1; writeMap[TemporaryMemoryId][despawnTimeId] = 1; writeMap[TemporaryMemoryId][initializeId] = 1; writeMap[TemporaryMemoryId][updateSequentialId] = 1; writeMap[TemporaryMemoryId][updateParallelId] = 1; writeMap[TemporaryMemoryId][terminateId] = 1; writeMap[TemporaryMemoryId][updateSpawnId] = 1; 
		readMap[TemporaryMemoryId][preprocessId] = 1; readMap[TemporaryMemoryId][spawnTimeId] = 1; readMap[TemporaryMemoryId][despawnTimeId] = 1; readMap[TemporaryMemoryId][initializeId] = 1; readMap[TemporaryMemoryId][updateSequentialId] = 1; readMap[TemporaryMemoryId][updateParallelId] = 1; readMap[TemporaryMemoryId][terminateId] = 1; readMap[TemporaryMemoryId][updateSpawnId] = 1; 
		return true;
	}();
};
